### ISSUE TITLE
Inability to Properly Manage Fund Reserves in Wallet

### ISSUE THREAD

**Issue by szwojtek** [DontTrustVerifyOrg/gig-gossip#57]
These issues include:
1. No Limit on Reservation Relative to Balance: Users can reserve any large integer, regardless of your account balance.
2. Allowing Transfers Despite Reserved Funds: The wallet permits users to make transfers even when funds are reserved.

**Comment by sonofsatoshi** [comment]
added CancelInvoiceSendPayment method
